# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0ef1490e48831dd1ef229540972b51881d300a8062507c9d06b1ba8c57a7906a72aa4ebb0dfb8b55e3bf55429120b49eec2df28a4fd3c06b2b1b5b3f123969a

test:
  secret_key_base: fa1e58bafb9fa96558fa2722f7432cd232198605b4483142ed081cda97d01b54901d9289027a401d18a2a9edb59f38053c949adfccc380353246517dc73ce7d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
